// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHsPb9c-0EvlURssxzWOYcMcS2PTfKX0',
    appId: '1:875133359456:web:446cf87a3b0f60592efa05',
    messagingSenderId: '875133359456',
    projectId: 'porto-d48b1',
    authDomain: 'porto-d48b1.firebaseapp.com',
    storageBucket: 'porto-d48b1.firebasestorage.app',
    measurementId: 'G-PDPRF9S8H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybW2ZqPFuB79a6IS1TKbQYMgU_Y-TYis',
    appId: '1:875133359456:android:246d4fb0b42b3a1e2efa05',
    messagingSenderId: '875133359456',
    projectId: 'porto-d48b1',
    storageBucket: 'porto-d48b1.firebasestorage.app',
  );
}
